# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles.active: local

  datasource:
    url: jdbc:h2:file:./data/wallet
    username: sa
    password: sa

  flyway.schema: wallet

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # muidu kustutab data ära!
    hibernate.ddl-auto: update

  h2.console.enabled: true

logging.level:
  root: INFO
